### ISSUE TITLE
Regression of config metrics

### ISSUE THREAD

**Issue by alex1989hu** [prometheus-community/pgbouncer_exporter#104]
PR: <https://github.com/prometheus-community/pgbouncer_exporter/pull/93>

Original comment: <https://github.com/prometheus-community/pgbouncer_exporter/pull/93#issuecomment-1405456997>

Dear @SuperQ and @kenneth-duffel I have been using `pgbouncer_exporter` for ages. I have just rebuilt it from master branch and I see in the logs:

```json
{"caller":"collector.go:474","err":"error retrieving columns list from SHOW CONFIG:  <nil>\n","level":"error","msg":"error getting SHOW CONFIG","ts":"2023-01-26T18:51:11.176Z"}
```

I have PgBouncer 1.17.0 where I have more than 3 colums:

```text
pgbouncer=# SHOW CONFIG;
            key            |                         value                         |                        default                         | changeable
---------------------------+-------------------------------------------------------+--------------------------------------------------------+------------
```

It should be at least 3, or do I miss something?

https://github.com/prometheus-community/pgbouncer_exporter/blob/07052df2990a5417d396cd5579721960cff8175e/collector.go#L189-L192

UPDATE: I found it, so the code expects these 3 columns in this order but I have `default` column as well before the `changeabl` value
https://github.com/prometheus-community/pgbouncer_exporter/blob/07052df2990a5417d396cd5579721960cff8175e/collector.go#L199-L201

Based on the documentation (https://www.pgbouncer.org/usage.html) there are 4 columns:

```text
SHOW CONFIG
Show the current configuration settings, one per row, with the following columns:

key
  Configuration variable name
value
  Configuration value
default
  Configuration default value
changeable
  Either yes or no, shows if the variable can be changed while running. If no, the variable can be changed only at boot time. 
Use SET to change a variable at run time.
```

**Comment by SuperQ** [comment]
Thanks for the report. It looks like we need to make the config handling a little more flexible for different versions.

**Comment by SuperQ** [comment]
Can you verify from the current master branch that the issue is fixed?

**Comment by stanhu** [comment]
@SuperQ I verified this with both PgBouncer 1.12 and 1.18. Thanks!
