### ISSUE TITLE
Trying to install the binary getting following error

### ISSUE THREAD

**Issue by anmoldukaan** [prometheus-community/pgbouncer_exporter#115]
build github.com/prometheus-community/pgbouncer_exporter: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
!! command failed: build -o /home/anmol_pandey/pgbouncer_exporter/pgbouncer_exporter -ldflags -X github.com/prometheus/common/version.Version=0.6.0 -X github.com/prometheus/common/version.Revision=8f44003fd8b0f2f13d49f11e256acd0596317c1d -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=anmol_pandey@dukaan-staging-db -X github.com/prometheus/common/version.BuildDate=20230502-08:00:00  -extldflags '-static' -a -tags 'netgo static_build' github.com/prometheus-community/pgbouncer_exporter: exit status 1
make: *** [Makefile.common:198: common-build] Error 1

OS: ubuntu 20.04

**Comment by SuperQ** [comment]
Your Go compiler is probably too old.
