### ISSUE TITLE
Why is the exporter creating an PVC in kubernetes

### ISSUE THREAD

**Issue by Skyhikeeper** [prometheus-community/pgbouncer_exporter#142]
I install the exporter using helm and it creates a 8Gb PVC. nowhere in the values have I configured it to persist to disk.

Terence

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by jz-wilson** [comment]
> I install the exporter using helm and it creates a 8Gb PVC. nowhere in the values have I configured it to persist to disk.
> 
> Terence

Hey I saw this same issue, idk if you resolved it yet buy you can add the following values to your helm release:
```yaml
postgresql:
  enabled: false
```

There is a postgresql dependency in the chart that is not needed for just the exporter.
