### ISSUE TITLE
pgbouncer_exporter Vulnerabilities

### ISSUE THREAD

**Issue by kaiossoares** [prometheus-community/pgbouncer_exporter#164]
Hello everyone!

The docker image "[timescaledb-ha](https://hub.docker.com/r/timescale/timescaledb-ha)"  i'm using has pgbouncer_exporter, however, I needed to scan the image using [Snyk](https://snyk.io/), pointing out problems in the version of the following package:

> ✗ High severity vulnerability found in golang.org/x/net/http2
>   Description: Allocation of Resources Without Limits or Throttling
>   Info: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285
>   Introduced through: golang.org/x/net/http2@v0.22.0
>   From: golang.org/x/net/http2@v0.22.0
>   Fixed in: 0.23.0
> 
> Package manager:   gomodules
> Target file:       /usr/local/bin/pgbouncer_exporter
> Project name:      github.com/prometheus-community/pgbouncer_exporter
> Docker image:      timescaledb-ha:latest
> Licenses:          enabled

Is it possible to have a release with the tag "0.9.0"? Probably the version of this package would be updated.

I am available and would like to contribute. Any help or advice would be appreciated.

**Comment by SuperQ** [comment]
We have cut a new release.
