### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by aek** [prometheus-community/pgbouncer_exporter#45]
I cannot find a Grafana Dashboard for this PgBouncer exporter that somehow it became the default option due to the mention in the Prometheus integration exporter list at:
https://prometheus.io/docs/instrumenting/exporters/

Does somebody have done any work on this topic that could be shared in this issue or uploaded into:
https://grafana.com/grafana/dashboards
Also it will be good to make references from this project to the Grafana dashboard and the same in the opposite way

**Comment by aek** [comment]
I'm playing with this one:
https://grafana.com/grafana/dashboards/10945
Trying to make it work

**Comment by nskalis** [comment]
Great initiative @aek 
Is https://grafana.com/grafana/dashboards/10945 final?

**Comment by aek** [comment]
I have publish it at: 
https://grafana.com/grafana/dashboards/14022
