### ISSUE TITLE
QUESTION: error pinging pgbouncer

### ISSUE THREAD

**Issue by nskalis** [prometheus-community/pgbouncer_exporter#53]
Hi,

Would you be so kind to advise how the connection string in `pgbouncer_exporter` works?
```
      --pgBouncer.connectionString="postgres://postgres:@localhost:6543/pgbouncer?sslmode=disable"  
                               Connection string for accessing pgBouncer.
```

For example, using the `psql` client to connect to the local `pgbouncer` instance
```
> psql --host=127.0.0.1 --port=6432 --dbname=pgbouncer --username=xxx
psql:/home/app/.psqlrc:1: NOTICE:  SET ignored
Timing is on.
Pager is always used.
Null display is "NULL".
psql (12.5, server 1.15.0/bouncer)
Type "help" for help.

xxx@127.0.0.1:6432 pgbouncer# \q
```
it succeeds.

Trying to do the same using `pgbouncer_exporter` results to an error
```
> /usr/local/sbin/pgbouncer_exporter --pgBouncer.connectionString="postgres://xxx:zzz@127.0.0.1:6432/pgbouncer?sslmode=disable"
level=error ts=2021-04-05T13:02:12.688Z caller=collector.go:129 msg="error setting up DB connection" err="error pinging pgbouncer: \"pq: unsupported startup parameter: extra_float_digits\""
```

Can you please advise?

**Comment by benjamin-bergia** [comment]
I am getting the same problem.

**Comment by stanhu** [comment]
You might want to try this config option: https://github.com/pgbouncer/pgbouncer/blob/e4beeab9c52d538075fbb5db0e5442cdf2fb90e5/etc/pgbouncer.ini#L154-L156

**Comment by nskalis** [comment]
I can confirm that the above option works :) thanks a lot @stanhu

**Comment by salmanbawazeer** [comment]
@nskalis  Can you please past down the example command you used to overcome the above issue.!!
