### ISSUE TITLE
Support running pgbouncer exporter over SSL

### ISSUE THREAD

**Issue by balasankarc** [prometheus-community/pgbouncer_exporter#82]
Other exporters seems to be using the `https` package in [exporter-toolkit](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md) to support running ove SSL. Can we implement something similar for pgbouncer_exporter also?

**Comment by SuperQ** [comment]
Yes, should be easy enough to implement.

**Comment by alex1989hu** [comment]
Dear @balasankarc it looks like @SuperQ addressed it, see in https://github.com/prometheus-community/pgbouncer_exporter/commit/2490f83639ab86bbad46df6fde6c6e843649a36f

**Comment by balasankarc** [comment]
@alex1989hu :+1: 

Also, Hi Ben. :) @SuperQ Thanks for the fix.
