### ISSUE TITLE
Add configuration via environment variables

### ISSUE THREAD

**Issue by EdgeJ** [prometheus-community/pgbouncer_exporter#94]
It would be helpful to be able to use environment variables to set configuration on the exporter. This is a fairly common pattern and absolutely necessary if running this as a sidecar in the Zalando pgsql operator, which currently only allows environment variables to be defined and prevents using command line arguments. I would be glad to put up a PR to add this functionality.

**Comment by jsirianni** [comment]
+1 I am dealing with this right now. I would like to inject credentials via environment variables + kubernetes secrets.

**Comment by SuperQ** [comment]
This is not the pattern we use for Prometheus exporters.

**Comment by jsirianni** [comment]
> This is not the pattern we use for Prometheus exporters.

Perhaps this is not the place to discuss it, but why is that? Exporters are incredibly popular in Docker / Kubernetes. Setting parameters via `command` and `args` is fine for most things but not ideal for secrets. Additionally, OP's platform requires environment variables.

Simply saying [we do not support this](https://github.com/prometheus-community/pgbouncer_exporter/pull/95#issuecomment-1405243445) or "this is not the pattern we use" without any explanation is discouraging.

**Comment by SuperQ** [comment]
This has been discussed many times within the Prometheus developer team.

We do sometimes support secrets via ENV, but they not really a safe option either. The best practice way to handle secrets is to pass a config file, especially with Kubernetes where `Secret` objects are an option. This would be a separate feature request than just "Support ENV vars".

**Comment by SuperQ** [comment]
For example, it's perfectly possible to pass ENV vars via args with `--some-flag=${ENV_VAR}`.
