### ISSUE TITLE
extra_float_digits problem

### ISSUE THREAD

**Issue by oculos** [prometheus-community/pgbouncer_exporter#99]
Hi,

When connecting, I get this:

ts=2023-01-09T14:32:54.310Z caller=collector.go:129 level=error msg="error setting up DB connection" err="error pinging pgbouncer: \"pq: unsupported startup parameter: extra_float_digits\""

Any clue on how to solve it? I know I can set pgbouncer to ignore extra_float_digits, but I'm afraid to break something, since the documentation says that newer JBDC drivers use it.

**Comment by maxzintel** [comment]
I am seeing this as well. 

Will follow up here if I find an easy solve.

**Comment by stanhu** [comment]
See https://github.com/prometheus-community/pgbouncer_exporter/issues/53#issuecomment-862482236.

**Comment by maxzintel** [comment]
Thanks @stanhu ! So, presumably I just set this flag in my pgbouncer config? Nothing needs to be changed on the exporter?

**Comment by maxzintel** [comment]
^ Confirmed that is the case! 

For anyone else using the bitnami/pgbouncer image in K8s, all you have to do is set `- PGBOUNCER_IGNORE_STARTUP_PARAMETERS="extra_float_digits"` on your configmap.
